### PR TITLE
docs: create doc to refactorings

### PR DESCRIPTION
**Pull request by tassioFront**
Refactoring makes part of JSMLover's way of being, doing it every day and task by task. We have good practices and conditions to do that, though.

### CODE REVIEW

**Review by felipefialho — APPROVED** [review]
👏 👏 👏 👏

**Review by deverebor — APPROVED** [review]

**Comment by deverebor** [comment]
off topic: At the request of MAy I studied vuex and with that I made some summaries, etc. Is it in this repository that I can share these summaries?

**Comment by tassioFront** [comment]
> off topic: At the request of May I studied vuex and with that I made some summaries, etc. Is it in this repository that I can share these summaries?

For sure, man! That sounds great! You can clone the repository and make it as well!

**Comment by schirrel** [comment]
hey buddy, do you mind at it on the  General Code Patterns summary also? like
1.1 Code Syntax
1.2 ...

**Comment by tassioFront** [comment]
> 

Oh great, man! I didn't see it. hehe Thanks @schirrel

**Review by schirrel — APPROVED** [review]

**Review by mauriciomutte — APPROVED** [review]

**Pull request merged**
