### PR TITLE
doc(testing): add tests with "it" section

### PR DESCRIPTION
**Pull request by mauriciomutte**

### CODE REVIEW

**Review by douglasffilho — APPROVED** [review]

**Comment by douglasffilho** [comment]
🚀

**Review by hick97 — APPROVED** [review]
Nice! Maybe we could create a topic to `should` prefix usage too 😄

**Comment by 3rdepaula** [comment]
It's nice to put this point in the guideline, but I also think it's interesting to just put in the description the reason for using "it", whether for performance, code readability, etc. If you think it makes clear sense =D

**Review by ldantas-s — APPROVED** [review]

**Review by HelenDias — APPROVED** [review]

**Review by schirrel — CHANGES_REQUESTED** [review]
Hey 🦣 is missing the `10. [Tests](#tests)` at summary 😅

**Review by schirrel — APPROVED** [review]

**Review by JulioCVaz — APPROVED** [review]

**Review by lupy100 — APPROVED** [review]

**Pull request merged**
