### PR TITLE
docs(test): adding test-id and find element

### PR DESCRIPTION
**Pull request by schirrel**
Hey, i've add out test-id approach created by the QA and also how to use it to find component during tests :hehe:

### CODE REVIEW

**Review by felipefialho — APPROVED** [review]
❤️ ❤️ ❤️

**Review by tassioFront — APPROVED** [review]
Way to go, boy! ❤️

**Review by hick97 — APPROVED** [review]
🚀

**Review by douglasffilho — APPROVED** [review]
LGTM

**Pull request merged**
